name: DCO Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DCO
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for DCO check to inspect all commits
      - name: DCO Sign Off Check
        uses: probot/dco@v2