name: dco

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify DCO sign-off in commits
        shell: bash
        run: |
          set -euo pipefail

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
            RANGE="$BASE..$HEAD"
          else
            BEFORE="${{ github.event.before }}"
            if [[ -z "${BEFORE}" || "${BEFORE}" =~ ^0+$ ]]; then
              RANGE="${{ github.sha }}"
            else
              RANGE="${BEFORE}..${{ github.sha }}"
            fi
          fi

          echo "Checking commits in range: $RANGE"
          COMMITS="$(git rev-list $RANGE || true)"
          if [[ -z "$COMMITS" ]]; then
            COMMITS="${{ github.sha }}"
          fi

          bad=0
          while read -r sha; do
            [[ -z "$sha" ]] && continue
            if ! git show -s --format=%B "$sha" | grep -qiE '^Signed-off-by: .+ <.+@.+>$'; then
              echo "::error::Commit $sha is missing a proper 'Signed-off-by:' trailer"
              echo "----- COMMIT MESSAGE ($sha) -----"
              git show -s --format='%B' "$sha"
              echo "---------------------------------"
              bad=1
            fi
          done <<< "$COMMITS"

          exit $bad
